import type { Metadata } from "next";
import "./globals.css";
import { MuseoModerno } from 'next/font/google'
import Script from "next/script";

const museoModerno = MuseoModerno({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Next Futbol Survey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/d4ba08446e.js" crossOrigin="anonymous"></Script>
        <body
          className={`${museoModerno.className} antialiased`}
        >
          {children}
        </body>
      </head>
    </html>
  );
}

